import {
  UserProfile,
  Task,
  SkillNode,
  SkillTreeCategory,
  FlowerPlant,
  RoomDecorItem,
  RewardItem,
  Achievement,
  JournalEntry,
  DailyXPLog
} from '../types';

export const INITIAL_USER: UserProfile = {
  id: 'user_1',
  name: 'Muskan',
  email: 'muskan@levelup.cozy',
  level: 1,
  currentXp: 0,
  coins: 0,
  currentStreak: 1,
  longestStreak: 1,
  todayGoalXp: 50,
  title: 'Novice Adventurer',
  avatar: {
    gender: 'cozy',
    hairstyle: 'soft_waves',
    hairColor: '#4A3E3D',
    outfit: 'pastel_sweater',
    accessory: 'cat_ears',
    expression: 'happy_smile',
    background: 'cozy_nook',
  },
};

export const DEFAULT_SKILL_TREES: SkillTreeCategory[] = [
  { id: 'JAVA', label: 'Core Java & Spring Boot', icon: '☕' },
  { id: 'DSA', label: 'Data Structures & Algorithms', icon: '⚡' },
  { id: 'MERN', label: 'React & MERN Stack', icon: '🌐' },
  { id: 'AIML', label: 'AI & Machine Learning', icon: '🤖' },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task_1',
    title: 'Understand Java Collections Framework (ArrayList vs LinkedList)',
    description: 'Read notes on Memory Layout, Time Complexities, and Iterator pattern in Collections.',
    category: 'Core Java',
    difficulty: 'EASY',
    xp: 10,
    coins: 5,
    completed: false,
    skillTag: 'Collections',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task_2',
    title: 'Solve "Two Sum" & "Valid Anagram" on LeetCode',
    description: 'Use HashMap for O(n) solution. Write down edge cases in your journal.',
    category: 'DSA',
    difficulty: 'MEDIUM',
    xp: 20,
    coins: 10,
    completed: false,
    skillTag: 'Arrays & Hashing',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task_3',
    title: 'Build Spring Boot REST API for LevelUp User Profile',
    description: 'Create UserEntity, UserRepository, UserService, and UserController with @RestController.',
    category: 'Java Full Stack',
    difficulty: 'HARD',
    xp: 40,
    coins: 20,
    completed: false,
    skillTag: 'Spring Boot',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task_4',
    title: 'Boss Battle 🐉: Complete Full Stack JWT Authentication Flow',
    description: 'Implement Spring Security Filter, JWT Token Generator, Login Controller & React Context.',
    category: 'Java Full Stack',
    difficulty: 'BOSS',
    xp: 100,
    coins: 50,
    completed: false,
    skillTag: 'Security',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task_5',
    title: 'Read 15 Pages of "Clean Code" or Tech Documentation',
    description: 'Focus on meaningful names and small functions. Cozy reading time with tea ☕',
    category: 'Reading',
    difficulty: 'EASY',
    xp: 10,
    coins: 5,
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task_6',
    title: '15-Minute Mindful Stretch or Evening Walk 🌿',
    description: 'Rest your eyes, step away from screens, and get fresh air.',
    category: 'Fitness',
    difficulty: 'EASY',
    xp: 10,
    coins: 5,
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task_7',
    title: 'Practice Binary Search Tree Traversal (Inorder, Preorder, Postorder)',
    description: 'Implement recursive and iterative approaches in Java.',
    category: 'DSA',
    difficulty: 'MEDIUM',
    xp: 20,
    coins: 10,
    completed: false,
    skillTag: 'Trees',
    createdAt: new Date().toISOString(),
  },
];

export const CORE_JAVA_SKILL_TREE: SkillNode[] = [
  {
    id: 'java_1',
    domain: 'JAVA',
    name: 'Core Java Fundamentals',
    description: 'Variables, Data Types, Control Statements, OOP Concepts (Encapsulation, Inheritance, Polymorphism).',
    levelRequired: 1,
    prerequisiteIds: [],
    unlocked: true,
    completed: false,
    icon: '☕',
    estimatedHours: 8,
    practiceQuests: ['Write Bank Account OOP class', 'Method Overloading vs Overriding exercise'],
  },
  {
    id: 'java_2',
    domain: 'JAVA',
    name: 'Collections Framework',
    description: 'List, Set, Map, Queue, ArrayList, HashMap, ConcurrentHashMap & Comparable vs Comparator.',
    levelRequired: 1,
    prerequisiteIds: ['java_1'],
    unlocked: true,
    completed: false,
    icon: '📦',
    estimatedHours: 10,
    practiceQuests: ['ArrayList vs LinkedList benchmarks', 'Custom HashMap Key implementation'],
  },
  {
    id: 'java_3',
    domain: 'JAVA',
    name: 'Exception Handling',
    description: 'Try-Catch-Finally, Checked vs Unchecked Exceptions, Try-With-Resources, Custom Exceptions.',
    levelRequired: 2,
    prerequisiteIds: ['java_2'],
    unlocked: true,
    completed: false,
    icon: '🛡️',
    estimatedHours: 6,
    practiceQuests: ['Build GlobalExceptionHandler', 'Custom InvalidUserException'],
  },
  {
    id: 'java_4',
    domain: 'JAVA',
    name: 'File Handling & Streams',
    description: 'Java I/O, NIO.2, Java 8 Stream API, Lambda Expressions, Optional, Functional Interfaces.',
    levelRequired: 2,
    prerequisiteIds: ['java_3'],
    unlocked: true,
    completed: false,
    icon: '🌊',
    estimatedHours: 8,
    practiceQuests: ['Filter and Map student grades with Streams', 'Read CSV File with BufferedReader'],
  },
  {
    id: 'java_5',
    domain: 'JAVA',
    name: 'JDBC & Database Connectivity',
    description: 'DriverManager, Connection, PreparedStatement, ResultSet, HikariCP Connection Pooling.',
    levelRequired: 3,
    prerequisiteIds: ['java_4'],
    unlocked: true,
    completed: false,
    icon: '🗄️',
    estimatedHours: 8,
    practiceQuests: ['Write PreparedStatement SQL Queries', 'Transaction Commit and Rollback'],
  },
  {
    id: 'java_6',
    domain: 'JAVA',
    name: 'Servlets & JSP',
    description: 'HttpServlet Lifecycle, RequestDispatcher, Session Management, Filter Chains.',
    levelRequired: 3,
    prerequisiteIds: ['java_5'],
    unlocked: false,
    completed: false,
    icon: '🌐',
    estimatedHours: 10,
    practiceQuests: ['Create LoginServlet with HttpSession', 'Authentication Filter Servlet'],
  },
  {
    id: 'java_7',
    domain: 'JAVA',
    name: 'Spring Framework Core',
    description: 'Dependency Injection (DI), Inversion of Control (IoC), Beans Lifecycle, Spring AOP.',
    levelRequired: 4,
    prerequisiteIds: ['java_6'],
    unlocked: false,
    completed: false,
    icon: '🌱',
    estimatedHours: 12,
    practiceQuests: ['@Autowired and @Qualifier usage', 'Logging Aspect with AOP'],
  },
  {
    id: 'java_8',
    domain: 'JAVA',
    name: 'Spring Boot REST & Data JPA',
    description: 'Auto-configuration, Spring Data JPA Repositories, REST Controllers, Jackson JSON Serialization.',
    levelRequired: 4,
    prerequisiteIds: ['java_7'],
    unlocked: false,
    completed: false,
    icon: '🚀',
    estimatedHours: 15,
    practiceQuests: ['CRUD REST Endpoints for Product Catalog', 'Derived JPA Query Methods'],
  },
  {
    id: 'java_9',
    domain: 'JAVA',
    name: 'Full Stack Integration Projects',
    description: 'React + Spring Boot Integration, CORS, DTO Mapping, Global Validation, Docker Compose.',
    levelRequired: 5,
    prerequisiteIds: ['java_8'],
    unlocked: false,
    completed: false,
    icon: '🏗️',
    estimatedHours: 20,
    practiceQuests: ['Connect React Vite to Spring Boot backend', 'Deploy application to Cloud Run'],
  },
  {
    id: 'java_10',
    domain: 'JAVA',
    name: 'Interview Ready Master',
    description: 'System Design basics, Java Concurrency (Threads, ExecutorService), JVM Memory Tuning, Spring Security JWT.',
    levelRequired: 5,
    prerequisiteIds: ['java_9'],
    unlocked: false,
    completed: false,
    icon: '👑',
    estimatedHours: 25,
    practiceQuests: ['Mock Java Tech Interview', 'JVM Garbage Collection Tuning'],
  },
];

export const INITIAL_GARDEN_PLANTS: FlowerPlant[] = [
  {
    id: 'plant_1',
    type: 'SAKURA',
    name: 'Cherry Blossom of Focus',
    stage: 3, // Full bloom
    growthPoints: 100,
    maxGrowthPoints: 100,
    wateredToday: true,
    plantedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'plant_2',
    type: 'SUNFLOWER',
    name: 'Sunny Determination',
    stage: 2, // Bud
    growthPoints: 60,
    maxGrowthPoints: 100,
    wateredToday: true,
    plantedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'plant_3',
    type: 'LAVENDER',
    name: 'Calm Mindfulness',
    stage: 1, // Sprout
    growthPoints: 30,
    maxGrowthPoints: 100,
    wateredToday: false,
    plantedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'plant_4',
    type: 'GOLDEN_LOTUS',
    name: 'Lotus of Consistency',
    stage: 0, // Seed
    growthPoints: 10,
    maxGrowthPoints: 100,
    wateredToday: false,
    plantedAt: new Date().toISOString(),
  },
];

export const INITIAL_ROOM_DECOR: RoomDecorItem[] = [
  {
    id: 'desk_oak',
    name: 'Warm Oak Wooden Desk',
    category: 'DESK',
    price: 0,
    unlocked: true,
    equipped: true,
    emoji: '🪵',
    color: '#8D5B4C',
    description: 'A cozy natural wood desk with smooth brass handles.',
  },
  {
    id: 'laptop_mac',
    name: 'Developer Laptop with Stickers',
    category: 'LAPTOP',
    price: 0,
    unlocked: true,
    equipped: true,
    emoji: '💻',
    color: '#718096',
    description: 'Decorated with cute Java & Spring Boot sticker badges.',
  },
  {
    id: 'cat_orange',
    name: 'Mochi the Purring Ginger Cat 🐱',
    category: 'PET',
    price: 50,
    unlocked: true,
    equipped: true,
    emoji: '🐱',
    color: '#ED8936',
    description: 'Sleeps soundly on your desk while you study.',
  },
  {
    id: 'plant_monstera',
    name: 'Giant Potted Monstera',
    category: 'PLANT',
    price: 30,
    unlocked: true,
    equipped: true,
    emoji: '🌿',
    color: '#38A169',
    description: 'Brings fresh air and cozy vibes to your study corner.',
  },
  {
    id: 'bookshelf_cozy',
    name: 'Grand Tech Bookshelf',
    category: 'SHELF',
    price: 60,
    unlocked: false,
    equipped: false,
    emoji: '📚',
    color: '#713F12',
    description: 'Stacked with Java, DSA, and System Design classics.',
  },
  {
    id: 'lamp_warm',
    name: 'Warm Honey Desk Lamp',
    category: 'LAMP',
    price: 40,
    unlocked: false,
    equipped: false,
    emoji: '💡',
    color: '#ECC94B',
    description: 'Casts a gentle, warm amber glow for night study sessions.',
  },
  {
    id: 'window_rain',
    name: 'Cozy Rain Window',
    category: 'WINDOW',
    price: 80,
    unlocked: false,
    equipped: false,
    emoji: '🌧️',
    color: '#4299E1',
    description: 'Gentle raindrops pattering against the glass.',
  },
];

export const INITIAL_REWARDS: RewardItem[] = [
  {
    id: 'rew_1',
    title: '15-Minute Gaming or Scroll Break 🎮',
    description: 'Enjoy guilt-free playtime or relaxing music.',
    cost: 20,
    icon: '🎮',
    category: 'BREAK',
    redeemedCount: 3,
  },
  {
    id: 'rew_2',
    title: 'Iced Boba Tea or Favorite Coffee 🧋',
    description: 'Treat yourself to a delicious refreshing drink.',
    cost: 50,
    icon: '🧋',
    category: 'TREAT',
    redeemedCount: 1,
  },
  {
    id: 'rew_3',
    title: 'Watch 1 Episode of Anime / Show 📺',
    description: 'Unwind with your favorite story.',
    cost: 40,
    icon: '📺',
    category: 'ENTERTAINMENT',
    redeemedCount: 2,
  },
  {
    id: 'rew_4',
    title: '30-Minute Power Nap 😴',
    description: 'Recharge your brain and energy.',
    cost: 30,
    icon: '😴',
    category: 'SELF_CARE',
    redeemedCount: 0,
  },
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach_1',
    title: 'First Step Adventurer 🌟',
    description: 'Complete your very first task on LevelUp.',
    icon: '🌱',
    unlocked: true,
    unlockedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    rewardCoins: 15,
    progress: 1,
    maxProgress: 1,
  },
  {
    id: 'ach_2',
    title: 'XP Scholar (100 XP) 🎓',
    description: 'Earn a total of 100 XP through learning.',
    icon: '⭐',
    unlocked: true,
    unlockedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    rewardCoins: 30,
    progress: 100,
    maxProgress: 100,
  },
  {
    id: 'ach_3',
    title: 'XP Master (1000 XP) 🏆',
    description: 'Accumulate 1,000 XP across all study quests.',
    icon: '👑',
    unlocked: false,
    rewardCoins: 100,
    progress: 285,
    maxProgress: 1000,
  },
  {
    id: 'ach_4',
    title: 'Cozy 7-Day Flame 🔥',
    description: 'Maintain a 7-day study streak with zero guilt.',
    icon: '🔥',
    unlocked: false,
    rewardCoins: 50,
    progress: 5,
    maxProgress: 7,
  },
  {
    id: 'ach_5',
    title: 'Core Java Pioneer ☕',
    description: 'Complete all Core Java skill nodes in the skill tree.',
    icon: '☕',
    unlocked: false,
    rewardCoins: 75,
    progress: 2,
    maxProgress: 10,
  },
  {
    id: 'ach_6',
    title: 'Garden Gardener 🌸',
    description: 'Grow at least 3 flowers to full bloom.',
    icon: '🌸',
    unlocked: true,
    rewardCoins: 40,
    progress: 3,
    maxProgress: 3,
  },
];

export const INITIAL_JOURNAL: JournalEntry[] = [
  {
    id: 'j_1',
    date: new Date(Date.now() - 86400000 * 1).toISOString().split('T')[0],
    mood: 'INSPIRED',
    oneLiner: 'Understood ArrayList memory reallocation & solved two HashMap problems!',
    reflection: 'Taking breaks every 30 minutes helped me stay focused without feeling drained.',
  },
  {
    id: 'j_2',
    date: new Date().toISOString().split('T')[0],
    mood: 'COZY',
    oneLiner: 'Learned Spring Boot Dependency Injection and watered my cherry blossom tree 🌸',
    reflection: 'Slow and steady progress is still progress.',
  },
];

export const INITIAL_DAILY_LOGS: DailyXPLog[] = [
  { date: '2026-07-16', xpGained: 20, tasksCompleted: 2, studyMinutes: 45 },
  { date: '2026-07-17', xpGained: 40, tasksCompleted: 3, studyMinutes: 75 },
  { date: '2026-07-18', xpGained: 30, tasksCompleted: 2, studyMinutes: 60 },
  { date: '2026-07-19', xpGained: 50, tasksCompleted: 4, studyMinutes: 90 },
  { date: '2026-07-20', xpGained: 35, tasksCompleted: 3, studyMinutes: 65 },
  { date: '2026-07-21', xpGained: 60, tasksCompleted: 4, studyMinutes: 110 },
  { date: '2026-07-22', xpGained: 50, tasksCompleted: 3, studyMinutes: 80 },
];
